ChainSafe/forest-explorer

.github/dependabot.yml, .github/workflows/deploy.yml, .github/workflows/test.yml, Cargo.lock, Cargo.toml, e2e/Cargo.lock, e2e/Cargo.toml, src/lib.rs
Changes:
- dependabot group for worker* crates
- check `cargo fmt` and `cargo clippy` in CI and fix current warnings
- run `cargo update`
- no `rust-cache` in CI since `sccache` is enabled
=> fix(deps): dependabot group for worker* crates

Cargo.lock, Cargo.toml, src/lib.rs, wrangler.toml
Host static assets with CloudFlare rather than embedding them into our WASM bundle. Also, add `quick` env for faster iterations.
Closes: #49
=> chore: host assets directly with cloudflare

src/app.rs, src/rpc_context.rs
`StateSearchMsg` may return `null`. If this happens, don't report it as an error.
=> fix: don't report pending transactions as errors

src/app.rs, src/faucet.rs, src/lib.rs, src/rate_limiter.rs, wrangler.toml
- Transactional rate-limiter. Cannot be defeated by rapid clicking!
- Disable the "Send" button when preparing the Filecoin transaction.
- Disable the "Send" button when rate limited.
=> fix: transactional rate-limiter

.gitignore, README.md, src/faucet/controller.rs, src/faucet/mod.rs, src/faucet/model.rs, src/faucet/utils.rs, src/faucet/views.rs, src/rpc_context.rs
- added some docs on the local environment + required bypass with rate limiter,
- separated the faucet into a rough Model-View-Controller - more work is needed, but my holidays are calling me :santa: 
- there were no changes in the faucet logic itself
Closes
(if possible),
=> chore: MVC faucet first blood

.config/forest.dic, .github/workflows/deploy.yml, .github/workflows/test.yml, README.md, package.json, rust-toolchain.toml, wrangler.toml, yarn.lock
- specify minimum node version in `package.json` (require >=18 as it's the oldest LTS version, although it should work with node 14+)
- drop `npx` usages and move scripts to `package.json` that is managed by `yarn@4.5.3` . This also locks tool(`wrangler`, `prettier`, `tailwindcss`, etc.) versions in `yarn.lock` to avoid future breakage.
- update docs accordingly
Closes #101
(if possible),
=> chore: specify minimum node version

README.md
- Document the full deployment procedure
Closes #74 
(if possible),
=> docs: document how to deploy the forest explorer on a clean CloudFlare account

src/app.rs, src/faucet/controller.rs, src/faucet/views.rs
- Use `Transition` instead of `Suspense` to avoid flickering back to "Loading..."
- Fixed flicker between faucet actual balance and empty balance
- Update target balance also once transaction is confirmed
Closes #116 
(if possible),
=> Fix flickering 

Cargo.lock, Cargo.toml, src/faucet/controller.rs, src/faucet/model.rs, src/faucet/views.rs, src/utils.rs, style/tailwind.css
- Add support for fading (and disappearing) messages
- Improve message display with the offensive address
Closes #89
(if possible),
=> Add support for fading messages

Cargo.lock
- fixes `openssl` vulnerability reported by `cargo deny` and blocking the CI
Closes
```
error[vulnerability]: ssl::select_next_proto use after free
┌─ /home/rumcajs/prj/forest-explorer/Cargo.lock:192:1
│
192 │ openssl 0.10.68 registry+https://github.com/rust-lang/crates.io-index
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ security vulnerability detected
│
├ ID: RUSTSEC-2025-0004
├ Advisory: https://rustsec.org/advisories/RUSTSEC-2025-0004
├ In `openssl` versions before `0.10.70`, `ssl::select_next_proto` can return a slice pointing into the `server` argument's buffer but with a lifetime bound to the `client` argument. In situations where the `server` buffer's lifetime is shorter than the `client` buffer's, this can cause …
```
=> fix: bump openssl version

src/rate_limiter.rs
- The Durable Object is clearing out its in-memory state more often than I expected. This PR moves the state into persistent storage.
Closes
(if possible),
=> fix: store 'block_until' in persistent storage

.github/workflows/deploy.yml, CHANGELOG.md, src/faucet/views.rs
- Show a `Request Faucet Top-up` option instead of send button if available faucet balance is less than network drip amount
Closes #129 
(if possible),
=> Request faucet top-up on low balance

CHANGELOG.md, src/constants.rs, src/faucet/controller.rs, src/faucet/utils.rs, src/faucet/views.rs, src/rate_limiter.rs
This reverts commit 7a327d3ca04b191d3e5053d3c84e2e8f82553f40.
- rate-limiting doesn't work correctly - I get rate limited on both calibnet and mainnet, even though both had last transaction over 2-3 days ago.
https://beryx.io/fil/calibration/address/t15ydyu3d65gznpp2qxwpkjsgz4waubeunn6upvla
https://beryx.io/fil/mainnet/address/f1j2al2ibxjpuy4ezamwd6exsftk6jlmqmdyivmui
Re-opens https://github.com/ChainSafe/forest-explorer/issues/137
(if possible),
=> Revert "Different rate limiter for calibnet and mainnet (#142)"

CHANGELOG.md, src/constants.rs, src/faucet/controller.rs, src/faucet/utils.rs, src/faucet/views.rs, src/rate_limiter.rs
- Fixed rate limiter issue with accessing network info from request path. 
[fix: ](https://github.com/ChainSafe/forest-explorer/pull/180/commits/3c6b61555628a5a730afc52c21918fb123594954) use `req.path()` instead of `req.url()`.
Closes #137 
(if possible),
=> Revive different rate limiter for mainnet and calibnet

public/robots.txt, public/sitemap.xml
[Forest Filecoin Explorer](https://forest-explorer.chainsafe.dev/) is currently missing a `robots.txt` file and an XML `sitemap`, both of which are important for effective search engine indexing and SEO.
- added `robots.txt` file
- added `sitemap.xml` file
➡️ **One thing that needs to be done after PR is merged:**
For additional context, please refer to the Filecoin Foundation UXIT [Filecoin Forest Explorer Faucet Report](https://filecoin.notion.site/Filecoin-Forest-Explorer-Faucet-Report-19d7631f2825802b8e53e53fe4cd747e).
(if possible),
[1]: …
=> Add sitemap and robots page

src/lib.rs
There is an issue with the newest axum update from https://github.com/ChainSafe/forest-explorer/pull/212
```
Path segments must not start with `*`.
For wildcard capture, use `{*wildcard}`.
If you meant to literally match a segment starting with an asterisk, call `without_v07_checks` on the router.
```
This PR resolves it as suggested by the error message. :) 
Closes
(if possible),
=> fix: axum 0.8 wildcards handling

.github/workflows/codecov.yml
To unblock https://github.com/ChainSafe/forest-explorer/pull/211 because external PRs have no access to `vars` and `secrets`
-
Closes
(if possible),
=> fix(ci): skip codecov upload for external PRs

e2e/script.js
- Increase timeout and remove `waitUntil` on page navigation to speedup the checks.
Closes
(if possible),
=> Fix E2E timeout error

e2e/script.js
- This might not be the best way to fix e2e flakiness, especially if we introduce more network events to the faucet, but it resolves the e2e flakiness that we experience at the moment. A better solution might come as a follow-up.
https://grafana.com/docs/k6/latest/javascript-api/k6-browser/page/waitfornavigation/#events
Closes
(if possible),
=> fix: wait for network idle in e2e

e2e/script.js, src/faucet/views/faucets/mod.rs
- addressed suggestions for the `Send` button in the FF UX report.
Closes https://github.com/ChainSafe/forest-explorer/issues/170
(if possible),
=> chore: improved send button text
