.gitignore
src/app.rs

- added build artifacts to gitignore
- removed the pre-defined wallet address

fix: remove pre-defined target wallet

---

.github/CODEOWNERS
.github/ISSUE_TEMPLATE/1-bug_report.md
.github/ISSUE_TEMPLATE/2-user_request.md
.github/ISSUE_TEMPLATE/3-epic.md
.github/ISSUE_TEMPLATE/4-task.md
.github/ISSUE_TEMPLATE/5-other.md
.github/ISSUE_TEMPLATE/config.yml
.github/PULL_REQUEST_TEMPLATE.md

Added some boilerplate:
- CODEOWNERS
- issue and PR templates

chore: add repo boilerplate templates

---

.github/workflows/deploy.yml
.github/workflows/test.yml

fix(ci): jobs are stuck in merge queue

---

src/app.rs
src/faucet.rs
src/message.rs
src/rpc_context.rs

- Transfer amount are now checked server-side
- Both mainnet and calibnet use the rate rate-limiter: 1 transfer every 30 seconds.

feat: mainnet faucet

---

src/app.rs

- Forest calibnet and mainnet faucet now live under distinct URLs. The former page serves as a landing page with available faucets.
Closes https://github.com/ChainSafe/forest-explorer/issues/69
(if possible),

feat: separate calibnet and mainnet

---

src/faucet/views.rs

- Add send on key Enter behavior for the text input
Closes #90
(if possible),

Enable sending tokens by pressing Enter

---

.config/forest.dic
src/app.rs
src/constants.rs
src/faucet/controller.rs
src/faucet/utils.rs
src/faucet/views.rs
src/lib.rs
src/rate_limiter.rs

- changed rate limit from 30s to 60s
- increased mainnet FIL drip from 0.001 FIL to 0.01 FIL (which should cover ~3 contract invocations)
- added a footer to all pages
- added descriptions to faucets
- moved some numbers scattered across the code to constants. We might consider making them configurable in the future if need be.
Closes https://github.com/ChainSafe/forest-explorer/issues/71
(if possible),

feat: change drip size, rate limit and add descriptions

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md

- added a changelog to commemorate the first release.
Closes https://github.com/ChainSafe/forest-explorer/issues/76
Closes https://github.com/ChainSafe/forest-explorer/issues/77
(if possible),

chore: first Forest Explorer release

---

src/rate_limiter.rs
wrangler.toml

- Enable logging and log all requests to the rate limiter.
Closes
(if possible),

chore: log rate-limiter state

---

CHANGELOG.md
src/constants.rs

- increased drip time to 10 minutes due to the mainnet faucet usage abuse.
Closes
(if possible),

chore: increase drip time to 10 minutes

---

Makefile
package.json
rust-toolchain.toml
yarn.lock

- resolves cargo deny issues https://github.com/ChainSafe/forest-explorer/actions/runs/13967433146/job/39103980746?pr=176
Closes
(if possible),

fix: pin cargo deny + update wrangler

---

CHANGELOG.md
src/app.rs
src/faucet/views.rs
src/rpc_context.rs

- Update the context  provider url when the faucet type is changed
Closes #91 
(if possible),

fix: message encoding based on network

---

CHANGELOG.md

- I fixed a formatting issue with the changelog. Outside of this PR, I also made the `lint` check required.
Closes
(if possible),

fix: changelog formatting

---

src/faucet/views.rs

- Remove `Effect::new` it's not required.
Closes #201 
(if possible),

Remove unused Effect::new

---

.config/forest.dic
README.md
wrangler.toml

- Update `Custom Deployment` steps in `README`.
Closes #178 
(if possible),

Update Custom Deployment in README 

---

src/app.rs

This PR updates the page title to be more descriptive and adds meta description to enhance SEO.
For additional context, please refer to the Filecoin Foundation UXIT [Filecoin Forest Explorer Faucet Report](https://filecoin.notion.site/Filecoin-Forest-Explorer-Faucet-Report-19d7631f2825802b8e53e53fe4cd747e).
(if possible),

Change title and add description

---

src/app.rs
src/icons/check_icon.rs
src/icons/lightning_icon.rs
src/icons/mod.rs
src/lib.rs

This PR enhance UI and content for better UX and SEO
(if possible),

Increase the word count to include at least 100 words of unique content

---

.github/workflows/lint.yml
Makefile

fix: run leptosfmt in `make fmt`

---

package.json
yarn.lock

- Use latest wrangler `v4.16.0`
Closes
(if possible),

bump wrangler from 4.15.2 to 4.16.0

---

.github/dependabot.yml
package.json
yarn.lock

- Use latest wrangler `4.18.0`
Closes
(if possible),

bump wrangler to 4.18.0

---

src/faucet/views/components/layout.rs
src/faucet/views/faucets/calibnet.rs
src/faucet/views/faucets/calibnet_usdfc.rs
src/faucet/views/faucets/mainnet.rs
src/faucet/views/faucets/mod.rs
style/tailwind.css

- Updated the Footer component to include new sections for "Learn More" and "Feedback & Support" with relevant links.
- Refactored the layout of the Faucet components to improve readability and maintainability by restructuring HTML elements.
- Adjusted CSS styles for better alignment and spacing, ensuring a more responsive design across different screen sizes.
(if possible),

Add new section to footer and improve overall layout structure

---

.config/forest.dic
README.md

- update the README with missing information around the USDFC wallet and its secret handling.
Closes
(if possible),

chore: update README with USDFC info

---

src/faucet/views/components/transaction.rs

- Use correct css class for tx links.
Closes #266 
(if possible),

Fix transaction link css
